### ISSUE TITLE
About time on database

### ISSUE THREAD

**Issue by BrunoDark2004** [Leone25/Sitelink#10]
Hii, in which format it's the time on the DB?
![print](https://user-images.githubusercontent.com/45894235/121886590-79ffac80-cd0d-11eb-8a92-6741acc6e142.PNG)~
And if it's possible to convert this to a more regular format, like 14-06-2020 12:40
(I'm new at this things, soo yeah)

**Comment by BrunoDark2004** [comment]
I notice that this is in Timestamp, but thanks!

**Comment by Leone25** [comment]
oh yea sorry lmao I did not receive notifications about this

but yea it's in timestamp format, it's the same given by discord
