### ISSUE TITLE
ER_BAD_NULL_ERROR - when nickname have for example "/" on name

### ISSUE THREAD

**Issue by greenpt2016** [Leone25/Sitelink#7]
Hello,

sorry to bring issues on  this, but i found that when the nickname is for example "name / name" it gives problems and the variable "user" stays null and gives back error on bot. For sure its because of the "/" that gives problems, is there any way of passing, or if necessary we can stay without the "/" on the nickname.
Thank you once again for your help (i write you on discord  my name is [deleted] you can add me please, i cant write you.

here is the error the bot gives:

  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlMessage: "Column 'user' cannot be null",
  sqlState: '23000',
  index: 0,
  sql: "INSERT INTO discord SET `message` = 'Confirmo', `id` = '701848274629296238', `time` = 1587404068382, `timeEdit` = '', `user` = NULL, `links` = '[]', `images` = '[]'"
}

**Comment by Leone25** [comment]
Sorry my bad, i forgot an or in the code, just pushed an updated that should fix it, the problem wasn't the / . . . just me being dumb.
